version : "3"
services :
  api :
    image : exercice
    build : .
    environment :
      - NODE_ENV=production
      - DB_URL=mongodb://mongo
    ports :
      - "9090:9090"
    networks :
      - app7
    depends_on :
      - mongo
  mongo :
    image : mongo:5
    networks :
      - app7
    ports :
      - "27017:27017"
    volumes :
      - database:/data/db
volumes:
  database:
networks:
  app7:

 #docker-compose up -d    : pour lancer le docker-compose
  #docker-compose down     : pour arrêter le docker-compose
  # badalt 7aja f server.js : DB_UR

